### Create author "Tatsuki Fujimoto"
POST http://localhost:8080/api/v1/authors
Content-Type: application/json

{
  "name": "Тацуки Фудзимото"
}

> {%
    client.global.set("author_id", response.body.id);
    client.global.set("author_slug", response.body.slug);
    client.log("Author ID: " + response.body.id);
    client.log("Slug: " + response.body.slug);
 %}

### Update author "Tatsuki Fujimoto"
PUT http://localhost:8080/api/v1/authors/{{author_id}}
Content-Type: application/json

{
  "countryIsoCode": "JP"
}

### Get author "Tatsuki Fujimoto" by id
GET http://localhost:8080/api/v1/authors/{{author_id}}
Content-Type: application/json

### Get author "Tatsuki Fujimoto" by slug
GET http://localhost:8080/api/v1/authors/slug/{{author_slug}}
Content-Type: application/json

### Get all authors
GET http://localhost:8080/api/v1/authors
Content-Type: application/json

### Delete author "Tatsuki Fujimoto"
DELETE http://localhost:8080/api/v1/authors/{{author_id}}
