### Create tag "Shonen"
POST http://localhost:8080/api/v1/tags
Content-Type: application/json

{
  "name": "Сёнэн",
  "slug": "shonen",
  "type": "GENRE",
  "description": ""
}

> {%
    client.global.set("shonen_tag_id", response.body.id);
    client.global.set("shonen_tag_slug", response.body.slug);
    client.log("Tag ID: " + response.body.id);
    client.log("Slug: " + response.body.slug);
 %}

### Create tag "Action"
POST http://localhost:8080/api/v1/tags
Content-Type: application/json

{
    "name": "Боевик",
    "slug": "",
    "type": "GENRE",
    "description": ""
}

> {%
    client.global.set("action_tag_id", response.body.id);
    client.log("Tag ID: " + response.body.id);
%}

### Update tag "Action"
PUT http://localhost:8080/api/v1/tags/{{action_tag_id}}
Content-Type: application/json

{
  "slug": "action"
}

### Get tag "Action" by id
GET http://localhost:8080/api/v1/tags/{{action_tag_id}}
Content-Type: application/json

### Get tag "Shonen" by slug
GET http://localhost:8080/api/v1/tags/slug/{{shonen_tag_slug}}
Content-Type: application/json

### Get all tags
GET http://localhost:8080/api/v1/tags
Content-Type: application/json

### Delete tag "Action"
DELETE http://localhost:8080/api/v1/tags/{{action_tag_id}}
