package dev.harakki.comics.analytics.domain;

public enum InteractionType {
    CHAPTER_READ,
    TITLE_LIKED,
    TITLE_DISLIKED,
    TITLE_VIEWED,
    TITLE_ADDED_TO_LIBRARY,
    TITLE_REMOVED_FROM_LIBRARY,
    TITLE_CREATED,
    TITLE_UPDATED,
    TITLE_DELETED,
    AUTHOR_CREATED,
    AUTHOR_UPDATED,
    AUTHOR_DELETED,
    PUBLISHER_CREATED,
    PUBLISHER_UPDATED,
    PUBLISHER_DELETED,
    CHAPTER_CREATED,
    CHAPTER_UPDATED,
    CHAPTER_DELETED,
    COLLECTION_CREATED,
    COLLECTION_UPDATED,
    COLLECTION_DELETED,
    TITLE_ADDED_TO_COLLECTION,
    TITLE_REMOVED_FROM_COLLECTION
}
